services:
    # nginx
    web:
        build:
          dockerfile: ./nginx/Dockerfile
        ports:
          - '80:80' #host:container
        volumes:
          - ./nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
    # php
    app:
        build:
            dockerfile: ./php/Dockerfile
        volumes:
           - ./app:/var/www/html
    # mysql
    db:
        image: mysql:8.0
        volumes:
            - mysqldata:/var/lib/mysql
        
        restart: unless-stopped
        environment:
            MYSQL_ROOT_PASSWORD: secret
            MYSQL_USER: user
            MYSQL_PASSWORD: secret
            MYSQL_DATABASE: docker-php
    # redis

volumes:
    mysqldata: